### ISSUE TITLE
Docker run is failing with exit code 1

### ISSUE THREAD

**Issue by Pavithrajas** [docker-practice/actions-setup-docker#14]
I am trying to test the GitHub actions in my local machine using [act](https://github.com/nektos/act)  with the docker setup. 

My workflow file is, 
```
name: Run Docker in Ubuntu
on: [push, pull_request]
jobs:
  sanity-check:
    runs-on: ubuntu-latest
    steps:
      - name: Run Docker
        uses: docker-practice/actions-setup-docker@master
```

For this, I am getting the following error, 

```
| [command]/usr/bin/sudo systemctl status docker
| System has not been booted with systemd as init system (PID 1). Can't operate.
| Failed to connect to bus: Host is down
[Sanity Check/sanity-check] ❗ ::error::Error: The process '/usr/bin/sudo' failed with exit code 1
[Sanity Check/sanity-check] ❌ Failure - Run Docker
```

Anyone else faced a similar problem or do we have any workaround to avoid this problem?
