### ISSUE TITLE
The latest version sometimes stuck on macos-latest

### ISSUE THREAD

**Issue by Morimiue** [docker-practice/actions-setup-docker#18]
See
- [https://github.com/dustincys/hithesis/actions/runs/2280840210](https://github.com/dustincys/hithesis/actions/runs/2280840210)

But sometimes it just works, for example:
- [https://github.com/dustincys/hithesis/actions/runs/2281872758](https://github.com/dustincys/hithesis/actions/runs/2281872758)

I dont know why. According to dapr/cli#965, I set the version to 1.0.8 and it seems work fine, at least for now.

**Comment by bpmct** [comment]
Has this been fixed?

edit: Ah, I see you can rollback

**Comment by Yurunsoft** [comment]
1.0.8, 1.0.9 are not working
https://github.com/Yurunsoft/php-tdengine/runs/6419048851?check_suite_focus=true

**Comment by douglascamata** [comment]
Seeing the same issue.

**Comment by kachkaev** [comment]
Weekly CI checks have been for a few months: https://github.com/docker-practice/actions-setup-docker/actions. Looks like this task no longer works on macOS 🤔 I tried `macos-latest`, `macos-11` and `macos-10.15` locally and also downgraded to `docker-practice/actions-setup-docker@1.0.8` (times when CI was green). This did not help.

Can anyone suggest alternative ways of running Docker on macOS in GitHub Actions?

**Comment by khs1994** [comment]
@kachkaev rollback to https://raw.githubusercontent.com/Homebrew/homebrew-cask/fe866ec0765de141599745f03e215452db7f511b/Casks/docker.rb

**Comment by kachkaev** [comment]
@khs1994 could you please elaborate on the alternative approach if you know it? Looks like I'm not the only person who struggles with running the action.

If the action can no longer work on `macos` — no worries at all, it'd be just great that folks had a new recipe available. I’ve been searching this topic for a few hours and this repo is pretty much everything that comes up as a solution.

**Comment by khs1994** [comment]
@kachkaev  
```yaml
on:
  push

name: ci

jobs:
  ci:
    runs-on: macos-12
    steps:
    - uses: docker-practice/actions-setup-docker@master
    - run: |
        set -x

        docker version

        docker run --rm hello-world
```

**Comment by kachkaev** [comment]
Thanks @khs1994! I must have misunderstood you when you shared the Homebrew link. I thought we'd need to use `brew install ...` ourselves instead of using the action. I just tried `macos-12` with `docker-practice/actions-setup-docker@1.0.11` and the workflow [got stuck again](https://github.com/blockprotocol/blockprotocol/runs/7730157923?check_suite_focus=true). See [related diff](https://github.com/blockprotocol/blockprotocol/pull/485/commits/36b0139336b81e93c746296b4f4f4e723c3a4322).

**Comment by douglascamata** [comment]
For those looking out for an alternative, I created https://github.com/douglascamata/setup-docker-action. I use Colima (Lima-VM under the hood) to set up Docker in macOS runners.

**Comment by kachkaev** [comment]
Thanks @douglascamata! I tried your action and it almost worked, I just missed `docker-compose`. Do you know a quick way of adding it?

I also tried new commit (https://github.com/docker-practice/actions-setup-docker/commit/82cea5df5890f0098e297b5f6f6c8d424ca406f6) – no luck so far.

**Comment by douglascamata** [comment]
@kachkaev to get `docker-compose` you just have to add a `run` step that will execute `brew install docker-compose` to your workflow.

**Comment by kachkaev** [comment]
Thanks @douglascamata! This worked:

```yml
      - name: Setup Docker on macOS
        uses: douglascamata/setup-docker-macos-action@v1-alpha

      - name: Install docker-compose
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install docker-compose
```

Actions took ≈ 4:15 and 0:10 seconds, respectively.

Hope to see `docker-practice/actions-setup-docker@master` fixed as well! 🤞
