### ISSUE TITLE
Add cache support or add example

### ISSUE THREAD

**Issue by mshima** [docker-practice/actions-setup-docker#21]
Caching should reduce failures.

I think third party actions supports caching.

In any case this implements caching at MacOS for the docker dmg.
```
      - name: 'SETUP MacOS: load Homebrew cache'
        uses: actions/cache@v3
        if: runner.os == 'macOS'
        with:
           path: |
             ~/Library/Caches/Homebrew/downloads/*--Docker.dmg
           key: brew-actions-setup-docker-1.0.11
           restore-keys: brew-actions-setup-docker-
```
I don't know where docker.rb is cached, but since it's stored at GitHub should not make too much difference.
