### ISSUE TITLE
Tcp support

### ISSUE THREAD

**Issue by shargon** [docker-practice/actions-setup-docker#37]
I tried:

```
   - name: Install Docker
      uses: docker-practice/actions-setup-docker@master
      with:
        docker_version: 25.0.4
        docker_daemon_json: "{\"hosts\": [\"tcp://0.0.0.0:2375\", \"unix:///var/run/docker.sock\"]}"
```

But it didn't work

```
check docker version
check docker systemd status
show default daemon json content
show daemon json content
  /usr/bin/sudo cat /etc/docker/daemon.json
  {"hosts": ["tcp://0.0.0.0:2375", "unix:///var/run/docker.sock"]}
/usr/bin/sudo systemctl restart docker
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xeu docker.service" for details.
Error: Error: The process '/usr/bin/sudo' failed with exit code 1
```
