### ISSUE TITLE
Any plans to support darwin/macOS arm64?

### ISSUE THREAD

**Issue by docktermj** [docker-practice/actions-setup-docker#38]
When running a GitHub action such as:

```yaml
jobs:
  my-job:
    runs-on: macos-latest
    :
      - name: install Docker
        uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
    :
```

Although the return is a "success", the following is shown in the log:
```console
Warning: only support macOS x86_64, os arch is arm64
```
and docker is not installed.

Are there any plans to support darwin/macOS arm64?
