### ISSUE TITLE
Fails on `install docker` step: Packages were downgraded and -y was used without --allow-downgrades.

### ISSUE THREAD

**Issue by andremandrade** [docker-practice/actions-setup-docker#39]
It's failing in a very basic usage on Github Actions:
```yaml
...
runs-on: ubuntu-latest
steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: docker-practice/actions-setup-docker@1.0.12
        timeout-minutes: 12
...
```
Error logs:
![image](https://github.com/user-attachments/assets/6308f37c-35b4-4bbb-b758-972cda61c033)
